dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - smartcontractkit/chainlink@1.3.0


compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
      - '@chainlink=smartcontractkit/chainlink@1.3.0'

    version: 0.8.0



dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}